name: Security Issue
description: Report a vulnerability
title: "[SECURITY] "
labels: [SECURITY]
body:
  - type: input
    id: version
    attributes:
      label: DiscOS version
      description: Select which version of DiscOS you are using
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: usage
    attributes:
      label: Usage
      description: Select the affected release type
      options:
        - Systemd service
        - Docker container
        - NPM package
        - Bug is not release-specific
        - Other (specify it below)
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Select the affected backend mode
      options:
        - Standalone
        - External backend
        - Not mode-specific
    validations:
      required: true

  - type: dropdown
    id: safemode
    attributes:
      label: Safe Mode
      description: Indicate if DiscOS is running in Safe Mode.
      options:
        - Enabled
        - Disabled
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the security issue
      description: An in-depth description of the vulnerability, it's impact, and how to reproduce it.
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Node.js version, related network settings, etc.
    validations:
      required: true