#!/bin/sh

msg=$(cat "$1")

if ! echo "$msg" | grep -qE '^(FEATURE|BUGFIX|SECURITY|DOCS|DEV|REFACTOR): .{1,}$'; then
  echo "Invalid commit message format! Please refer to https://github.com/BrNi05/DiscOS/wiki/Contributing-to-DiscOS#coding"
  exit 1
fi