#!/bin/sh

BRANCH=$(git symbolic-ref --short HEAD)

if [ "$BRANCH" = "main" ]; then
  echo "Permission denied! Please refer to https://github.com/BrNi05/DiscOS/wiki/Contributing-to-DiscOS#coding"
  exit 1
fi